### PR TITLE
add not sorted info

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @Yu-jinKim)

___
*[`gff2tsv.py` line 249 at r1](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9#-N2GyNYP2Zd1yrDRvCp-:-N2GyNYP2Zd1yrDRvCp0:b-zh07zk) ([raw file](https://github.com/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/blob/6012785b96e12910ecea7cb0ac127f680852beb0/gff2tsv.py#L249)):*
> ```Python
>                 ])
> 
>     sorted_data = natsorted(data_to_write, key=lambda x: (x[0], x[1], x[2]))
> ```

I assume this is by chrom, pos ref? comment pls

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`gff2tsv.py` line 234 at r1](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9#-N2GyYu--tgp6IpE3lfO:-N2GyYu--tgp6IpE3lfP:b-m0nyf) ([raw file](https://github.com/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/blob/0716de6c1995b5b34107350a3fda51201262f8f4/gff2tsv.py#L234)):*
> ```Python
>                 feature_nb = data[feature][0].id.split("-")[-1]
> 
>                 f.write(
> ```

are these just indentation changes?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`gff2tsv.py` line 234 at r1](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9#-N2GyYu--tgp6IpE3lfO:-N2Gygac1Wde_XZ7ZDKk:b32x1t) ([raw file](https://github.com/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/blob/0716de6c1995b5b34107350a3fda51201262f8f4/gff2tsv.py#L234)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

are these just indentation changes?
</blockquote></details>

ye
___
*[`gff2tsv.py` line 249 at r1](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9#-N2GyNYP2Zd1yrDRvCp-:-N2GypVK4LoYY76u5iIh:b-896fix) ([raw file](https://github.com/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/blob/6012785b96e12910ecea7cb0ac127f680852beb0/gff2tsv.py#L249)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I assume this is by chrom, pos ref? comment pls
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/exon_file_and_g2t_from_new_refseq_gff/9#-:-N2Gz9acCEm5gIOCGpXn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
