### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
can you add a requirements.txt file

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-:-Mz_7l552ZOWedBFMR1H:b-cn7uay)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[gff2bed.py, line 50 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_77qb2ZYUbgOef4yq:-Mz_77qb2ZYUbgOef4yr:b-o1ye0u) ([raw file](https://github.com/eastgenomics/gff2bed/blob/0f028f1ff40df897c3ffbd358473eff8d37ee61d/gff2bed.py#L50)):*
> ```Python
>                 # if there is none or multiple we don't want it
>                 if len(hgnc_list) == 1:
>                     hgnc_id = ":".join(hgnc_list[0].split(":")[-2:])
> ```

what does this do? can you add comment with the structure of what you're splitting?
___
*[gff2bed.py, line 77 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_7ZG8DIKnfBuzUwIX:-Mz_7ZG8DIKnfBuzUwIY:bgoscrb) ([raw file](https://github.com/eastgenomics/gff2bed/blob/0f028f1ff40df897c3ffbd358473eff8d37ee61d/gff2bed.py#L77)):*
> ```Python
>         name = Path(path.name.split(".")[0])
> 
>         suffixes_to_keep = [
> ```

what does this do? is it just to remove `.gff.gz` from the filename for naming the output bed?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[gff2bed.py, line 50 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_77qb2ZYUbgOef4yq:-Mz_9CnZ46ZNUyQ5wWLQ:b-896fix) ([raw file](https://github.com/eastgenomics/gff2bed/blob/0f028f1ff40df897c3ffbd358473eff8d37ee61d/gff2bed.py#L50)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what does this do? can you add comment with the structure of what you're splitting?
</blockquote></details>

Done.
___
*[gff2bed.py, line 77 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_7ZG8DIKnfBuzUwIX:-Mz_8PLBB8FAIjoF5ii0:b-5tkt9o) ([raw file](https://github.com/eastgenomics/gff2bed/blob/0f028f1ff40df897c3ffbd358473eff8d37ee61d/gff2bed.py#L77)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what does this do? is it just to remove `.gff.gz` from the filename for naming the output bed?
</blockquote></details>

the name of the gff is `GCF_000001405.25_GRCh37.p13_genomic.gff.gz` so i'm trying to keep everything except `.gff.gz`

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[gff2bed.py, line 50 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_77qb2ZYUbgOef4yq:-Mz_A0b26eIHyvvOXxV4:bk0fun) ([raw file](https://github.com/eastgenomics/gff2bed/blob/0f028f1ff40df897c3ffbd358473eff8d37ee61d/gff2bed.py#L50)):*
ahh that makes sense, tiny thing but `split()` takes a number to split so can be simpler:
```
>>> s="HGNC:HGNC:1"
>>> s.split(":", 1)[-1]
'HGNC:1'
```



_Code quote:_
```Python
HGNC:HGNC:1
```
___
*[gff2bed.py, line 77 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_7ZG8DIKnfBuzUwIX:-Mz_AI9C9JXKpt5BxouU:b-wnx9pl) ([raw file](https://github.com/eastgenomics/gff2bed/blob/0f028f1ff40df897c3ffbd358473eff8d37ee61d/gff2bed.py#L77)):*
> GCF_000001405.25_GRCh37.p13_genomic.gff.gz
why not just do 
```
>>> s="GCF_000001405.25_GRCh37.p13_genomic.gff.gz"
>>> s.replace(".gff", "").replace(".gz", "")
'GCF_000001405.25_GRCh37.p13_genomic'
```

or all in one
```
>>> name=f'{s.replace(".gff", "").replace(".gz", "")}.bed'
>>> name
'GCF_000001405.25_GRCh37.p13_genomic.bed'
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[gff2bed.py, line 50 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_77qb2ZYUbgOef4yq:-Mz_BDJM2-PFz-6-jDjd:b-8xw6dz) ([raw file](https://github.com/eastgenomics/gff2bed/blob/0f028f1ff40df897c3ffbd358473eff8d37ee61d/gff2bed.py#L50)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

ahh that makes sense, tiny thing but `split()` takes a number to split so can be simpler:
```
>>> s="HGNC:HGNC:1"
>>> s.split(":", 1)[-1]
'HGNC:1'
```
</blockquote></details>

it's magic
___
*[gff2bed.py, line 77 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_7ZG8DIKnfBuzUwIX:-Mz_BS0t4VAfYcncv_ws:bxm4tem) ([raw file](https://github.com/eastgenomics/gff2bed/blob/0f028f1ff40df897c3ffbd358473eff8d37ee61d/gff2bed.py#L77)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> GCF_000001405.25_GRCh37.p13_genomic.gff.gz
why not just do 
```
>>> s="GCF_000001405.25_GRCh37.p13_genomic.gff.gz"
>>> s.replace(".gff", "").replace(".gz", "")
'GCF_000001405.25_GRCh37.p13_genomic'
```

or all in one
```
>>> name=f'{s.replace(".gff", "").replace(".gz", "")}.bed'
>>> name
'GCF_000001405.25_GRCh37.p13_genomic.bed'
```
</blockquote></details>

i guess i didn't think of it

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[gff2bed.py, line 6 at r2](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_BcCoB8hpRgWfIbqa:-Mz_BcCoB8hpRgWfIbqb:b3bil9x) ([raw file](https://github.com/eastgenomics/gff2bed/blob/b71abc52aabd6071ea1845f78e3423eade995f30/gff2bed.py#L6)):*
> ```Python
> import gffutils
> 
> # replace refseq chrom by "normal" chrom names
> ```

is `MT` or any other weird contigs etc present? 
___
*[gff2bed.py, line 48 at r2](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_BroyABZ6XZP7Entm:-Mz_BroyABZ6XZP7Entn:be5n7u) ([raw file](https://github.com/eastgenomics/gff2bed/blob/b71abc52aabd6071ea1845f78e3423eade995f30/gff2bed.py#L48)):*
> ```Python
>                 ]
> 
>                 # if there is none or multiple we don't want it
> ```

why would there be none or multiple? what happens with these?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[gff2bed.py, line 6 at r2](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_BcCoB8hpRgWfIbqa:-Mz_Cuue25iK8wDsvkyh:b-2ptklb) ([raw file](https://github.com/eastgenomics/gff2bed/blob/b71abc52aabd6071ea1845f78e3423eade995f30/gff2bed.py#L6)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is `MT` or any other weird contigs etc present? 
</blockquote></details>

there's scaffolds in there
___
*[gff2bed.py, line 48 at r2](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_BroyABZ6XZP7Entm:-Mz_C-q4Anx2zx55bnvT:b-9600i4) ([raw file](https://github.com/eastgenomics/gff2bed/blob/b71abc52aabd6071ea1845f78e3423eade995f30/gff2bed.py#L48)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why would there be none or multiple? what happens with these?
</blockquote></details>

there shouldn't be multiple because HGNC ids but if there's none, i discard them which is not the safest but I'm unsure how to handle exons without hgnc ids.
But in comparing the output from the script and g2t, no genes from nirvana were absent in VEP

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[gff2bed.py, line 50 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_77qb2ZYUbgOef4yq:-Mz_OVtHDlGsLjyNtX4w:bpvuamj) ([raw file](https://github.com/eastgenomics/gff2bed/blob/0f028f1ff40df897c3ffbd358473eff8d37ee61d/gff2bed.py#L50)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

it's magic
</blockquote></details>

doesn't need the first `":".join(...` as you're selecting a single index from the split so its just a string
___
*[gff2bed.py, line 6 at r2](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_BcCoB8hpRgWfIbqa:-Mz_OqWj8ItEoAfs9wYL:bkhtz0n) ([raw file](https://github.com/eastgenomics/gff2bed/blob/b71abc52aabd6071ea1845f78e3423eade995f30/gff2bed.py#L6)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

there's scaffolds in there
</blockquote></details>

do they also need handling or not?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[gff2bed.py, line 48 at r2](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-Mz_BroyABZ6XZP7Entm:-Mz_QRow5xfO26FLN8xq:b-tlejp0) ([raw file](https://github.com/eastgenomics/gff2bed/blob/b71abc52aabd6071ea1845f78e3423eade995f30/gff2bed.py#L48)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

there shouldn't be multiple because HGNC ids but if there's none, i discard them which is not the safest but I'm unsure how to handle exons without hgnc ids.
But in comparing the output from the script and g2t, no genes from nirvana were absent in VEP
</blockquote></details>

fair enough, maybe slap a print in if its not 1 just so its obvious

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1#-:-Mz_aglb7QoQ8M2zQstp:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
