### PR TITLE
convert to use cds

### PR DESCRIPTION
**Pull request by Yu-jinKim**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/3)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
can you update the readme with more information on what it does, and what the required input files are /  where they are from

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-:-N-NF__LCbfxHf1ZVga4:bjuoj0w)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[gff2bed.py, line 103 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-N-NElGN5osoTWaSVRHj:-N-NElGN5osoTWaSVRHk:bulr7po) ([raw file](https://github.com/eastgenomics/gff2bed/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L103)):*
> ```Python
> 
>                 else:
>                     exon_nb = None
> ```

do we need to handle / record what is none? Do we risk missing things here?
___
*[gff2bed.py, line 109 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-N-NEw9R3OpLXS7oYdWx:-N-NEw9R3OpLXS7oYdWy:bldoenp) ([raw file](https://github.com/eastgenomics/gff2bed/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L109)):*
> ```Python
> 
>             # check if exons for cds and check that there is only one
>             if cds in cds_w_exon_nb and len(cds_w_exon_nb[cds]) != 1:
> ```

this probably should be an assertion then it will raise the error for you and exit
___
*[gff2bed.py, line 121 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-N-NF6BfAe0cgEfrq4G0:-N-NF6BfAe0cgEfrq4G1:bq5voso) ([raw file](https://github.com/eastgenomics/gff2bed/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L121)):*
> ```Python
> def filter_out_features(feature):
>     """ Filter out features that have:
>         - contig chrom
> ```

what is `contig chrom`? is it the same as `feature.chrom` below?

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/3)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[gff2bed.py, line 59 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-N-NFnPc7wDEfJNd8iKs:-N-NFnPc7wDEfJNd8iKt:b-mzhhr1) ([raw file](https://github.com/eastgenomics/gff2bed/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L59)):*
> ```Python
> 
>     for feature in db.features_of_type(feature_type):
>         # check if feature has multiple parents
> ```

what are features in this context? do we need handle `!=1` ? (do any even have not 1 and why)

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/3)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[gff2bed.py, line 59 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-N-NFnPc7wDEfJNd8iKs:-N-NH9tM6wrCRh8xPz7u:bk9co3e) ([raw file](https://github.com/eastgenomics/gff2bed/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L59)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what are features in this context? do we need handle `!=1` ? (do any even have not 1 and why)
</blockquote></details>

Features can be cds or exons.
The != 1 is just a sanity check
___
*[gff2bed.py, line 103 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-N-NElGN5osoTWaSVRHj:-N-NH2Pi-NmxxPpqTGhJ:b-ndbqms) ([raw file](https://github.com/eastgenomics/gff2bed/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L103)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

do we need to handle / record what is none? Do we risk missing things here?
</blockquote></details>

I don't think so, I'm only getting exons with overlaps if not i want to discard them
___
*[gff2bed.py, line 109 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-N-NEw9R3OpLXS7oYdWx:-N-NGw9y5CsxwyI064U5:bl7cr37) ([raw file](https://github.com/eastgenomics/gff2bed/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L109)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this probably should be an assertion then it will raise the error for you and exit
</blockquote></details>

I wanna keep it that way to have prints and keep the exit
___
*[gff2bed.py, line 121 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-N-NF6BfAe0cgEfrq4G0:-N-NGmew61Dpqssr-lwu:bu0oz0d) ([raw file](https://github.com/eastgenomics/gff2bed/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L121)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

what is `contig chrom`? is it the same as `feature.chrom` below?
</blockquote></details>

I'm only getting NC chromosomes:
NC_	Genomic	Complete genomic molecule, usually reference assembly
NT_	Genomic	Contig or scaffold, clone-based or WGSa
NW_	Genomic	Contig or scaffold, primarily WGSa

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2bed/3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @Yu-jinKim)

___
*[gff2bed.py, line 121 at r1](https://reviewable.io/reviews/eastgenomics/gff2bed/3#-N-NF6BfAe0cgEfrq4G0:-N-NQ2cuAidmpmtchSJm:b-tz7mpg) ([raw file](https://github.com/eastgenomics/gff2bed/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L121)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

I'm only getting NC chromosomes:
NC_	Genomic	Complete genomic molecule, usually reference assembly
NT_	Genomic	Contig or scaffold, clone-based or WGSa
NW_	Genomic	Contig or scaffold, primarily WGSa
</blockquote></details>

can you add that somewhere (docstring or readme)

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/3)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[gff2bed.py, line 121 at r1](https://reviewable.io/reviews/eastgenomics/gff2tsv/3#-N-NF6BfAe0cgEfrq4G0:-N-NVoK4--1RrBcFXaXm:b-896fix) ([raw file](https://github.com/eastgenomics/gff2tsv/blob/51fd8ef754189be0e3e8c68a3228d90463bfba43/gff2bed.py#L121)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

can you add that somewhere (docstring or readme)
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/3#-:-N-OG4eT0JmmRRr1Zx-j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
