### PR TITLE
Lots of changes

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Remove Y chrom CDSes
- Handle 1 base pair CDSes
- Get CDSes with mRNA as parents only
- Remove duplicate exons bash script

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/4)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/4)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @Yu-jinKim)

___
*[remove_duplicated_exons.sh, line 14 at r1](https://reviewable.io/reviews/eastgenomics/gff2tsv/4#-N01ZQY62WdY3c2M_lnW:-N01ZQY62WdY3c2M_lnX:b-890x0z) ([raw file](https://github.com/eastgenomics/gff2tsv/blob/9905b972763d8c35222700ae20e27d294278654e/remove_duplicated_exons.sh#L14)):*
> ```Shell
> fi
> 
> # get transcripts to remove:
> ```

why do you get these? do you only get instances of 2 of the same?

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/4)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[remove_duplicated_exons.sh, line 14 at r1](https://reviewable.io/reviews/eastgenomics/gff2tsv/4#-N01ZQY62WdY3c2M_lnW:-N05_wOS3XJgZRKSleNp:b-896fix) ([raw file](https://github.com/eastgenomics/gff2tsv/blob/9905b972763d8c35222700ae20e27d294278654e/remove_duplicated_exons.sh#L14)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

why do you get these? do you only get instances of 2 of the same?
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/4)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[gff2tsv.py, line 188 at r3](https://reviewable.io/reviews/eastgenomics/gff2tsv/4#-N064A-dDfestayWjv5X:-N064A-dDfestayWjv5Y:b3lk28p) ([raw file](https://github.com/eastgenomics/gff2tsv/blob/f6b29d8d4afdb4230abc3bdbcf147f0386a111f6/gff2tsv.py#L188)):*
> ```Python
>     df = pd.DataFrame(list_of_transcripts_exons)
>     # get duplicated exons and get the corresponding transcripts into a list
>     transcripts_to_remove = df[df.duplicated()]["transcript"].to_list()
> ```

does this get both instances of a duplicate? is this what you want?
___
*[gff2tsv.py, line 228 at r3](https://reviewable.io/reviews/eastgenomics/gff2tsv/4#-N063svE0fib3Ac5dhbV:-N063svE0fib3Ac5dhbW:bnc0qyn) ([raw file](https://github.com/eastgenomics/gff2tsv/blob/f6b29d8d4afdb4230abc3bdbcf147f0386a111f6/gff2tsv.py#L228)):*
does this actually work? aren't you checking a str against a list of dicts?

```
>>> l=[]
>>> l.append({'a':1, 'b':2})
>>> l
[{'a': 1, 'b': 2}]
>>> 'a' in l
False
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/4)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[gff2tsv.py, line 188 at r3](https://reviewable.io/reviews/eastgenomics/gff2tsv/4#-N064A-dDfestayWjv5X:-N064VUcDWuSLlgWS9cV:b-2kpoj7) ([raw file](https://github.com/eastgenomics/gff2tsv/blob/f6b29d8d4afdb4230abc3bdbcf147f0386a111f6/gff2tsv.py#L188)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this get both instances of a duplicate? is this what you want?
</blockquote></details>

keep{‘first’, ‘last’, False}, default ‘first’
Determines which duplicates (if any) to mark.

first : Mark duplicates as True except for the first occurrence.

So it should mark the first occurrence of duplicatedness whether it's one or more.
I want to get the exons that are duplicated to get the transcript so i think it's fine
___
*[gff2tsv.py, line 228 at r3](https://reviewable.io/reviews/eastgenomics/gff2tsv/4#-N063svE0fib3Ac5dhbV:-N0657DOEJ3iaL2RyEK4:b-ca8wip) ([raw file](https://github.com/eastgenomics/gff2tsv/blob/f6b29d8d4afdb4230abc3bdbcf147f0386a111f6/gff2tsv.py#L228)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this actually work? aren't you checking a str against a list of dicts?

```
>>> l=[]
>>> l.append({'a':1, 'b':2})
>>> l
[{'a': 1, 'b': 2}]
>>> 'a' in l
False
```
</blockquote></details>

no transcripts to remove is a list

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/4)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/gff2tsv/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
